language: rust

rust:
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

script: cargo build && cargo build --features disable_float && sh scripts/travis-update.sh
